name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Automáticos
      id: test-automaticos
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Automáticos
        setup-command: ''
        command: bash autotest.sh
        timeout: 3
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-AUTOMATICOS_RESULTS: "${{steps.test-automaticos.outputs.result}}"
      with:
        runners: test-automaticos
